atc_first_level_full_list = {
    "A": "Alimentary Tract and Metabolism",
    "B": "Blood and Blood Forming Organs",
    "C": "Cardiovascular System",
    "D": "Dermatologicals",
    "G": "Genito Urinary System and Sex Hormones",
    "H": "Systemic Hormonal Preparations, Excl. Sex Hormones",
    "J": "Antiinfectives for Systemic Use",
    "L": "Antineoplastic and Immunomodulating Agents",
    "M": "Musculo-Skeletal System",
    "N": "Nervous System",
    "P": "Antiparasitic Products, Insecticides and Repellents",
    "R": "Respiratory System",
    "S": "Sensory Organs",
    "V": "Various",
}

atc_second_level_full_list = {
    "A": {
        "A01": "Stomatological Preparations",
        "A02": "Drugs for Acid-Related Disorders",
        "A03": "Drugs for Functional Gastrointestinal Disorders",
        "A04": "Antiemetics and Antinauseants",
        "A05": "Bile and Liver Therapy",
        "A06": "Drugs for Constipation",
        "A07": "Antidiarrheals, Intestinal Anti-inflammatory/Anti-infective Agents",
        "A08": "Antiobesity Preparations, Excl. Diet Products",
        "A09": "Digestives, Incl. Enzymes",
        "A10": "Drugs Used in Diabetes",
        "A11": "Vitamins",
        "A12": "Mineral Supplements",
        "A13": "Tonics",
        "A14": "Anabolic Agents for Systemic Use",
        "A15": "Appetite Stimulants",
        "A16": "Other Alimentary Tract and Metabolism Products",
    },
    "B": {
        "B01": "Antithrombotic Agents",
        "B02": "Antihemorrhagics",
        "B03": "Antianemic Preparations",
        "B05": "Blood Substitutes and Perfusion Solutions",
        "B06": "Other Hematological Agents",
    },
    "C": {
        "C01": "Cardiac Therapy",
        "C02": "Antihypertensives",
        "C03": "Diuretics",
        "C04": "Peripheral Vasodilators",
        "C05": "Vasoprotectives",
        "C07": "Beta Blocking Agents",
        "C08": "Calcium Channel Blockers",
        "C09": "Agents Acting on the Renin-Angiotensin System",
        "C10": "Lipid Modifying Agents",
    },
    "D": {
        "D01": "Antifungals for Dermatological Use",
        "D02": "Emollients and Protectives",
        "D03": "Preparations for Treatment of Wounds and Ulcers",
        "D04": "Antipruritics, Incl. Antihistamines, Anesthetics, etc.",
        "D05": "Antipsoriatics",
        "D06": "Antibiotics and Chemotherapeutics for Dermatological Use",
        "D07": "Corticosteroids, Dermatological Preparations",
        "D08": "Antiseptics and Disinfectants",
        "D09": "Medicated Dressings",
        "D10": "Anti-Acne Preparations",
        "D11": "Other Dermatological Preparations",
    },
    "G": {
        "G01": "Gynecological Antiinfectives and Antiseptics",
        "G02": "Other Gynecologicals",
        "G03": "Sex Hormones and Modulators of the Genital System",
        "G04": "Urologicals",
    },
    "H": {
        "H01": "Pituitary and Hypothalamic Hormones and Analogues",
        "H02": "Corticosteroids for Systemic Use",
        "H03": "Thyroid Therapy",
        "H04": "Pancreatic Hormones",
        "H05": "Calcium Homeostasis",
    },
    "J": {
        "J01": "Antibacterials for Systemic Use",
        "J02": "Antimycobacterials",
        "J04": "Antimycotics for Systemic Use",
        "J05": "Antivirals for Systemic Use",
        "J06": "Immunosuppressants",
        "J07": "Vaccines",
    },
    "L": {
        "L01": "Antineoplastic Agents",
        "L02": "Endocrine Therapy",
        "L03": "Immunostimulants",
        "L04": "Immunosuppressants",
    },
    "M": {
        "M01": "Antiinflammatory and Antirheumatic Products",
        "M02": "Topical Products for Joint and Muscular Pain",
        "M03": "Muscle Relaxants",
        "M04": "Antigout Preparations",
        "M05": "Drugs Used for Treatment of Bone Diseases",
        "M09": "Other Drugs for Disorders of the Musculo-Skeletal System",
    },
    "N": {
        "N01": "Anesthetics",
        "N02": "Analgesics",
        "N03": "Antiepileptics",
        "N04": "Antiparkinson Drugs",
        "N05": "Psycholeptics",
        "N06": "Psychoanaleptics",
        "N07": "Other Nervous System Drugs",
    },
    "P": {
        "P01": "Antiprotozoals",
        "P02": "Antihelminthics",
        "P03": "Ectoparasiticides, Incl. Scabicides, Insecticides and Repellents",
    },
    "R": {
        "R01": "Nasal Preparations",
        "R02": "Throat Preparations",
        "R03": "Drugs for Obstructive Airway Diseases",
        "R05": "Cough and Cold Preparations",
        "R06": "Antihistamines for Systemic Use",
        "R07": "Other Respiratory System Products",
    },
    "S": {
        "S01": "Ophthalmologicals",
        "S02": "Otic Products",
        "S03": "Ophthalmological and Otic Preparations",
    },
    "V": {
        "V01": "Allergens",
        "V03": "All Other Therapeutic Products",
        "V04": "Diagnostic Agents",
        "V06": "General Nutritional Products",
        "V07": "All Other Non-Therapeutic Products",
        "V08": "Contrast Media",
        "V09": "Diagnostic Radiopharmaceuticals",
        "V10": "Therapeutic Radiopharmaceuticals",
        "V20": "Surgical Dressings",
    },
}
